################################################
## This file and all its content belong to Faveod S.A.S unless a commercial
## contract signed by a representant of Faveod S.A.S states otherwise.
##############
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################
## This has been generated by Faveod Generator on Wed Sep 11 14:33:56 +0200 2013
## It should be placed at 'Gemfile'
## All manual modifications will be destroyed on next generation
################################################

source 'http://rubygems.org'

gem 'rails', '3.2.14'


gem 'awesome_nested_set', '> 2', :require => 'awesome_nested_set'
gem 'chronic'
gem 'fastercsv', :require => 'faster_csv'
gem 'mime-types', :require => 'mime/types'
gem 'spreadsheet'
gem 'fast_gettext'
gem 'will_paginate', '~> 3'
gem 'rmagick', :require => 'RMagick', :platforms => [:ruby]
gem 'mysql2', :platforms => [:ruby]
gem 'builder'
gem 'gettext', :group => :development
gem 'pdfkit', :require => 'pdfkit'
gem 'rdoc', :group => :development
gem 'ruby-prof', :group => :test, :platforms => [:ruby]
gem 'yaml_db'
gem 'rubyzip', :require => 'zip/zipfilesystem'
gem 'geokit-rails3'
gem 'acts_as_list'
gem 'uuid', '2.3.5'
gem 'activerecord-jdbcmysql-adapter', :platforms => [:jruby]
gem 'rmagick4j', :require => 'RMagick', :platforms => [:jruby]
gem 'acts_as_ferret', '>= 0.5'
gem 'grosser-get_pomo', :require => 'get_pomo'
gem 'keeguon-acts_as_versioned', :require => 'acts_as_versioned'
gem 'soap4r-spox', :platforms => [:ruby_19]
gem 'fakefs', :require => 'fakefs/safe'
gem 'rspec-rails', :group => :test, :platforms => [:ruby_19]
gem 'database_cleaner', :group => :test, :platforms => [:ruby_19]
