# encoding: utf-8
################################################
## This file and all its content belong to Faveod S.A.S unless a commercial
## contract signed by a representant of Faveod S.A.S states otherwise.
##########
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################
## This has been generated by Faveod Generator on Thu Oct 31 16:40:24 +0100 2013
## It should be placed at 'app/helpers/dev_feedbacks_helper.rb'
## All manual modifications will be destroyed on next generation
################################################


module DevFeedbacksHelper


  # Generally used for list actions.
  #
  # Author:: Yann Azoury
  # Version:: 12
  # Last Update:: 2013-01-29 23:35:49 UTC
  # Status:: Validation Pending


  def links_for_list_element(row, opts={})
    return "" if @no_row_links
    html = []
    if @pres_mode == :list_zoom
      html << link_to_remote(image_tag('std/show.png', :title => _('Show')),
      :url => {:controller => :dev_feedbacks, :action => :show, :id => row.id},
      :update => "dev_feedbacks_element")
      html << link_to_remote(image_tag('std/edit.png', :title => _('Edit')),
      :url => {:controller => :dev_feedbacks, :action => :edit, :id => row.id},
      :update => "dev_feedbacks_element")
    else
      html << if @pres_mode == :list_zoom
        %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('dev_feedbacks_element', '#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/show/#{ row.id }', {asynchronous:true, evalScripts:true});location.href='#dev_feedbacks_element'; return false;" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/show.png" alt="#{ _(%q{Show}) }" title="#{ _(%q{Show}) }" /></a>}
      else
        %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/show/#{ row.id }" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/show.png" alt="#{ _(%q{Show}) }" title="#{ _(%q{Show}) }" /></a>}
      end
      html << if @pres_mode == :list_zoom
        %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('dev_feedbacks_element', '#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/edit/#{ row.id }', {asynchronous:true, evalScripts:true});location.href='#dev_feedbacks_element'; return false;" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/page_icons/page_white_paintbrush.png" alt="#{ _(%q{Edit}) }" title="#{ _(%q{Edit}) }" /></a>}
      else
        %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/edit/#{ row.id }" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/page_icons/page_white_paintbrush.png" alt="#{ _(%q{Edit}) }" title="#{ _(%q{Edit}) }" /></a>}
      end
      html << nil
    end
    html << if @pres_mode == :list_zoom
      %Q{<a href="#" data-confirm="#{ _('Do you really want to delete %{record}?') %
      {:record => @dev_feedback.disp_name} }" data-method="post" onclick="new Ajax.Updater('dev_feedbacks_element', '#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/destroy/#{ @dev_feedback.id }', {asynchronous:true, evalScripts:true});location.href='#dev_feedbacks_element'; return false;" title="#{ _(%q{Deletes an object or list of objects from the database.}) }"><img src="/images/page_icons/cancel.png" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" /></a>}
    else
      %Q{<a data-confirm="#{ _('Do you really want to delete %{record}?') %
      {:record => @dev_feedback.disp_name} }" data-method="post" href="#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/destroy/#{ @dev_feedback.id }" title="#{ _(%q{Deletes an object or list of objects from the database.}) }"><img src="/images/page_icons/cancel.png" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" /></a>}
    end
    return html.compact.join(' | ').html_safe
  end


  # Author:: Sylvain Abélard
  # Version:: 17
  # Last Update:: 2013-03-19 15:06:38 UTC
  # Status:: Validation Pending


  def bottom_links_for_show(opts={})

    links = []
    if request.xhr?
      links << link_to_remote(image_tag('std/edit.png', :title => _("Edit")), :update => 'dev_feedbacks_element', :url => {:action => :edit, :id => @dev_feedback, :version => params[:version]})
    else
      links << if @pres_mode == :list_zoom
        %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('dev_feedbacks_element', '#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/edit/#{ @dev_feedback.id }', {asynchronous:true, evalScripts:true});location.href='#dev_feedbacks_element'; return false;" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/page_icons/page_white_paintbrush.png" alt="#{ _(%q{Edit}) }" title="#{ _(%q{Edit}) }" /> #{ _(%q{Edit}) }</a>}
      else
        %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/edit/#{ @dev_feedback.id }" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/page_icons/page_white_paintbrush.png" alt="#{ _(%q{Edit}) }" title="#{ _(%q{Edit}) }" /> #{ _(%q{Edit}) }</a>}
      end
    end
    links << if @pres_mode == :list_zoom
      %Q{<a href="#" data-confirm="#{ _('Do you really want to delete %{record}?') % {:record => @dev_feedback.disp_name} }" data-method="post" onclick="new Ajax.Updater('dev_feedbacks_element', '#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/destroy/#{ @dev_feedback.id }', {asynchronous:true, evalScripts:true});location.href='#dev_feedbacks_element'; return false;" title="#{ _(%q{Deletes an object or list of objects from the database.}) }"><img src="/images/page_icons/cancel.png" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" /> #{ _(%q{Destroy}) }</a>}
    else
      %Q{<a data-confirm="#{ _('Do you really want to delete %{record}?') % {:record => @dev_feedback.disp_name} }" data-method="post" href="#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/destroy/#{ @dev_feedback.id }" title="#{ _(%q{Deletes an object or list of objects from the database.}) }"><img src="/images/page_icons/cancel.png" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" /> #{ _(%q{Destroy}) }</a>}
    end
    links << if @pres_mode == :list_zoom
      %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('dev_feedbacks_element', '#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/index', {asynchronous:true, evalScripts:true});location.href='#dev_feedbacks_element'; return false;" rel="nofollow" title="#{ _(%q{Index of all dev_feedbacks.}) }"><img src="/images/page_icons/comments.png" alt="#{ _(%q{Dev Feedbacks}) }" title="#{ _(%q{Dev Feedbacks}) }"/> #{ _(%q{Dev Feedbacks}) }</a>}
    else
      %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/index" rel="nofollow" title="#{ _(%q{Index of all dev_feedbacks.}) }"><img src="/images/page_icons/comments.png" alt="#{ _(%q{Dev Feedbacks}) }" title="#{ _(%q{Dev Feedbacks}) }"/> #{ _(%q{Dev Feedbacks}) }</a>}
    end
    unless opts[:no_sibling]
      prev = DevFeedback.first(:select => '`dev_feedbacks`.id', :conditions => ["`dev_feedbacks`.id < ?", @dev_feedback.id], :order => '`dev_feedbacks`.id DESC')
      nex = DevFeedback.first(:select => '`dev_feedbacks`.id', :conditions => ["`dev_feedbacks`.id > ?", @dev_feedback.id], :order => '`dev_feedbacks`.id')
      if request.xhr?
        links << link_to_remote(image_tag('std/go_left.png', :title => _("Previous")), :update => 'dev_feedbacks_element', :url => {:action => :show, :id => prev.id}) if prev
        links << link_to_remote(image_tag('std/go_right.png', :title => _("Next")), :update => 'dev_feedbacks_element', :url => {:action => :show, :id => nex.id}) if nex
      else
        if prev
          links << if @pres_mode == :list_zoom
            %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('dev_feedbacks_element', '#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/show/#{ prev.id }', {asynchronous:true, evalScripts:true});location.href='#dev_feedbacks_element'; return false;" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/go_left.png" alt="#{ _(%q{Previous}) }" title="#{ _(%q{Previous}) }"/></a>}
          else
            %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/show/#{ prev.id }" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/go_left.png" alt="#{ _(%q{Previous}) }" title="#{ _(%q{Previous}) }"/></a>}
          end
        end
        if nex
          links << if @pres_mode == :list_zoom
            %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('dev_feedbacks_element', '#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/show/#{ nex.id }', {asynchronous:true, evalScripts:true});location.href='#dev_feedbacks_element'; return false;" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/go_right.png" alt="#{ _(%q{Next}) }" title="#{ _(%q{Next}) }"/></a>}
          else
            %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/show/#{ nex.id }" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/go_right.png" alt="#{ _(%q{Next}) }" title="#{ _(%q{Next}) }"/></a>}
          end
        end
      end
    end
    return content_tag(:span, links.compact.join(' | ').html_safe, :class => 'std_links')
  end


  # Author:: Sylvain Abélard
  # Version:: 17
  # Last Update:: 2013-03-19 15:06:52 UTC
  # Status:: Validation Pending


  def bottom_links_for_edit(opts={})

    links = []
    if request.xhr?
      links << link_to_remote(image_tag('std/show.png', :title => _('Show')), :update => 'dev_feedbacks_element', :url => {:action => :show, :id => @dev_feedback, :version => params[:version]})
    else
      links << if @pres_mode == :list_zoom
        %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('dev_feedbacks_element', '#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/show/#{ @dev_feedback.id }', {asynchronous:true, evalScripts:true});location.href='#dev_feedbacks_element'; return false;" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/show.png" alt="#{ _(%q{Show}) }" title="#{ _(%q{Show}) }" /> #{ _(%q{Show}) }</a>}
      else
        %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/show/#{ @dev_feedback.id }" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/show.png" alt="#{ _(%q{Show}) }" title="#{ _(%q{Show}) }" /> #{ _(%q{Show}) }</a>}
      end
    end
    links << if @pres_mode == :list_zoom
      %Q{<a href="#" data-confirm="#{ _('Do you really want to delete %{record}?') % {:record => @dev_feedback.disp_name} }" data-method="post" onclick="new Ajax.Updater('dev_feedbacks_element', '#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/destroy/#{ @dev_feedback.id }', {asynchronous:true, evalScripts:true});location.href='#dev_feedbacks_element'; return false;" title="#{ _(%q{Deletes an object or list of objects from the database.}) }"><img src="/images/page_icons/cancel.png" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" /> #{ _(%q{Destroy}) }</a>}
    else
      %Q{<a data-confirm="#{ _('Do you really want to delete %{record}?') % {:record => @dev_feedback.disp_name} }" data-method="post" href="#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/destroy/#{ @dev_feedback.id }" title="#{ _(%q{Deletes an object or list of objects from the database.}) }"><img src="/images/page_icons/cancel.png" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" /> #{ _(%q{Destroy}) }</a>}
    end
    links << if @pres_mode == :list_zoom
      %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('dev_feedbacks_element', '#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/index', {asynchronous:true, evalScripts:true});location.href='#dev_feedbacks_element'; return false;" rel="nofollow" title="#{ _(%q{Index of all dev_feedbacks.}) }"><img src="/images/page_icons/comments.png" alt="#{ _(%q{Dev Feedbacks}) }" title="#{ _(%q{Dev Feedbacks}) }"/> #{ _(%q{Dev Feedbacks}) }</a>}
    else
      %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/index" rel="nofollow" title="#{ _(%q{Index of all dev_feedbacks.}) }"><img src="/images/page_icons/comments.png" alt="#{ _(%q{Dev Feedbacks}) }" title="#{ _(%q{Dev Feedbacks}) }"/> #{ _(%q{Dev Feedbacks}) }</a>}
    end
    prev = DevFeedback.first(:select => '`dev_feedbacks`.id', :conditions => ["`dev_feedbacks`.id < ?", @dev_feedback.id], :order => '`dev_feedbacks`.id DESC')
    nex = DevFeedback.first(:select => '`dev_feedbacks`.id', :conditions => ["`dev_feedbacks`.id > ?", @dev_feedback.id], :order => '`dev_feedbacks`.id')
    if request.xhr?
      links << link_to_remote(image_tag('std/go_left.png', :title => _('Previous')), :update => 'dev_feedbacks_element', :url => {:action => :edit, :id => prev.id}) if prev
      links << link_to_remote(image_tag('std/go_right.png', :title => _('Next')), :update => 'dev_feedbacks_element', :url => {:action => :edit, :id => nex.id}) if nex
    else
      if prev
        links << if @pres_mode == :list_zoom
          %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('dev_feedbacks_element', '#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/edit/#{ prev.id }', {asynchronous:true, evalScripts:true});location.href='#dev_feedbacks_element'; return false;" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/std/go_left.png" alt="#{ _(%q{Previous}) }" title="#{ _(%q{Previous}) }"/></a>}
        else
          %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/edit/#{ prev.id }" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/std/go_left.png" alt="#{ _(%q{Previous}) }" title="#{ _(%q{Previous}) }"/></a>}
        end
      end
      if nex
        links << if @pres_mode == :list_zoom
          %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('dev_feedbacks_element', '#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/edit/#{ nex.id }', {asynchronous:true, evalScripts:true});location.href='#dev_feedbacks_element'; return false;" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/std/go_right.png" alt="#{ _(%q{Next}) }" title="#{ _(%q{Next}) }"/></a>}
        else
          %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/dev_feedbacks/edit/#{ nex.id }" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/std/go_right.png" alt="#{ _(%q{Next}) }" title="#{ _(%q{Next}) }"/></a>}
        end
      end
    end
    return content_tag(:span, links.compact.join(' | ').html_safe, :class => 'std_links')
  end


  # Icon Links to Tree Actions.
  #
  # Author:: Yann Azoury
  # Version:: 17
  # Last Update:: 2012-02-19 17:00:31 UTC
  # Status:: Could be optimized


  def tree_actions(row)
    html = [link_to(image_tag('std/edit.png'), :controller => :dev_feedbacks, :action => :edit, :id => row.id)]
    html << link_to(image_tag('std/del.png'),
    {:controller => :dev_feedbacks, :action => :destroy, :id => row.id},
    :remote => true,
    :confirm => _("Are you sure that you want to delete %{name}?") % {:name => row.disp_name})
    c = DevFeedback.get_root.children
    html << link_to(image_tag('std/go_up.png'),
    {:controller => :dev_feedbacks, :action => :tree_move, :id => row.id, :direction => :prev},
    :update => "dev_feedback_#{row.parent_id || 0}_div", :remote => true) if row.self_and_siblings.first != row || (row.parent.nil? && c.first != row)
    html << link_to(image_tag('std/go_down.png'),
    {:controller => :dev_feedbacks, :action => :tree_move, :id => row.id, :direction => :next},
    :update => "dev_feedback_#{row.parent_id || 0}_div", :remote => true) if row.self_and_siblings.last != row || (row.parent.nil? && c.last != row)
    html << link_to(image_tag('std/go_left.png'),
    {:controller => :dev_feedbacks, :action => :tree_move, :id => row.id, :direction => :dec},
    :update => "dev_feedback_#{row.parent.parent_id || 0}_div", :remote => true) unless row.parent.nil?
    html << link_to(image_tag('std/go_right.png'),
    {:controller => :dev_feedbacks, :action => :tree_move, :id => row.id, :direction => :inc},
    :update => "dev_feedback_#{row.left_sibling.id}_div",
    :loaded => %Q[$("dev_feedback_#{row.id}_div").remove()],
    :position => :bottom, :remote => true) if row.left_sibling
    return content_tag(:span, html.join.html_safe, :class => 'tree_actions', :id => "#{row.id}_actions")
  end


  # Render all ancestors with links.
  #
  # Author:: Yann Azoury
  # Version:: 6
  # Last Update:: 2012-01-25 01:32:58 UTC
  # Status:: Validation Pending


  def nested_set_full_outline(item,options={})
    return '' if item.nil?
    options = {
      :action => options[:action] || :show,
      :controller => options[:controller] || item.class.to_s.underscore,
    :separator => options[:separator] || ' &gt; '.html_safe }
    s = []
    for it in item.ancestors
      if block_given?
        s << yield(it) + options[:separator]
      else
        s << link_to(it.disp_name, { :controller => options[:controller], :action => options[:action], :id => it }) + options[:separator]
      end
    end
    if block_given?
      s << yield(item)
    else
      s << h(item.disp_name)
    end unless options[:parent_only]
    return s.join.html_safe
  end


  # Displays details about series
  #
  # Author:: Sylvain Abélard
  # Version:: 1
  # Last Update:: 2009-10-05 13:31:56 UTC
  # Status:: In Progress


  def series_details(s, txt=nil)
    return 'empty' if s.blank?
    info = "#{s.calculation}"
    info << " of #{s.field.name}" if s.field
      info << " by #{s.key_field.name}" if s.key_field
        details = txt || info
        content_tag(:span,
        content_tag(:span, '&nbsp;&nbsp;&nbsp;', :style => "background-color: #{s.html_color}; border: 1px inset gray;") +
        " #{s.disp_name} [#{details}]",
        :title => info,
        :class => "report_#{s.serie_type.downcase}")
      end


      # Author:: Sylvain Abélard
      # Version:: 1
      # Last Update:: 2010-03-01 20:39:30 UTC
      # Status:: In Progress


      def nested_set_options_for_select(class_or_item, options=nil)
        first_item = class_or_item.is_a?(Class) ? class_or_item.roots : class_or_item
        return [] if first_item.nil?

        # exclude some items and all their children

        if options.is_a? Hash
          text_column = options[:text_column]
          options.delete_if { |key, value| key != :exclude }
        else
          options = nil
        end

        # text_column ||= class_or_item.acts_as_nested_set_options[:text_column]

        if first_item.is_a?(Array)
          tree = first_item.flatten
        else
          tree = first_item.self_and_descendants
        end
        if block_given?
          tree.map{|item| [yield(item), item.id] }
        else
          tree.map{|item| [ "#{'··' * item.level}#{item.disp_name}", item.id]}
        end
      end

    end
