# -*- encoding : utf-8 -*-
################################################
## This file and all its content belong to Faveod S.A.S unless a commercial
## contract signed by a representant of Faveod S.A.S states otherwise.
##########
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################
## This has been generated by Faveod Generator on Sun Apr 28 21:54:22 +0200 2013
## It should be placed at 'app/helpers/translations_helper.rb'
## All manual modifications will be destroyed on next generation
################################################


module TranslationsHelper


  # Generally used for list actions.
  #
  # Author:: Yann Azoury
  # Version:: 12
  # Last Update:: 2013-01-29 23:35:49 UTC
  # Status:: <%= _(%q{Validation Pending}) %>


  def links_for_list_element(row, opts={})
    return "" if @no_row_links
    html = []
    if @pres_mode == :list_zoom
      html << link_to_remote(image_tag('std/show.png', :title => _('Show')),
      :url => {:controller => :translations, :action => :show, :id => row.id},
      :update => "translations_element")
      html << link_to_remote(image_tag('std/edit.png', :title => _('Edit')),
      :url => {:controller => :translations, :action => :edit, :id => row.id},
      :update => "translations_element")
    else
      html << nil
      html << nil
      html << nil
    end
    html << if @pres_mode == :list_zoom
      %Q{<a href="#" data-confirm="#{ _('Do you really want to delete %{record}?') %
      {:record => @translation.disp_name} }" data-method="post" onclick="new Ajax.Updater('translations_element', '#{ "/#{params[:lang]}" if params[:lang] }/translations/destroy/#{ @translation.id }', {asynchronous:true, evalScripts:true});location.href='#translations_element'; return false;"><img src="/images/default/s.gif" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" width="16" /></a>}
    else
      %Q{<a data-confirm="#{ _('Do you really want to delete %{record}?') %
      {:record => @translation.disp_name} }" data-method="post" href="#{ "/#{params[:lang]}" if params[:lang] }/translations/destroy/#{ @translation.id }"><img src="/images/default/s.gif" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" width="16" /></a>}
    end
    return html.compact.join(' | ').html_safe
  end


  # Author:: Sylvain Abélard
  # Version:: 17
  # Last Update:: 2013-03-19 15:06:38 UTC
  # Status:: <%= _(%q{Validation Pending}) %>


  def bottom_links_for_show(opts={})

    links = []
    if request.xhr?
      links << link_to_remote(image_tag('std/edit.png', :title => _("Edit")), :update => 'translations_element', :url => {:action => :edit, :id => @translation, :version => params[:version]})
    else
      links << nil
    end
    links << if @pres_mode == :list_zoom
      %Q{<a href="#" data-confirm="#{ _('Do you really want to delete %{record}?') % {:record => @translation.disp_name} }" data-method="post" onclick="new Ajax.Updater('translations_element', '#{ "/#{params[:lang]}" if params[:lang] }/translations/destroy/#{ @translation.id }', {asynchronous:true, evalScripts:true});location.href='#translations_element'; return false;"><img src="/images/default/s.gif" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" width="16" /> #{ _(%q{Destroy}) }</a>}
    else
      %Q{<a data-confirm="#{ _('Do you really want to delete %{record}?') % {:record => @translation.disp_name} }" data-method="post" href="#{ "/#{params[:lang]}" if params[:lang] }/translations/destroy/#{ @translation.id }"><img src="/images/default/s.gif" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" width="16" /> #{ _(%q{Destroy}) }</a>}
    end
    links << if @pres_mode == :list_zoom
      %Q{<a href="#" onclick="new Ajax.Updater('translations_element', '#{ "/#{params[:lang]}" if params[:lang] }/translations/index', {asynchronous:true, evalScripts:true});location.href='#translations_element'; return false;"><img src="/images/page_icons/anchor.png" alt="#{ _(%q{Translations}) }" title="#{ _(%q{Translations}) }"/> #{ _(%q{Translations}) }</a>}
    else
      %Q{<a href="#{ "/#{params[:lang]}" if params[:lang] }/translations/index"><img src="/images/page_icons/anchor.png" alt="#{ _(%q{Translations}) }" title="#{ _(%q{Translations}) }"/> #{ _(%q{Translations}) }</a>}
    end
    unless opts[:no_sibling]
      prev = Translation.first(:select => '`translations`.id', :conditions => ["`translations`.id < ?", @translation.id], :order => '`translations`.id DESC')
      nex = Translation.first(:select => '`translations`.id', :conditions => ["`translations`.id > ?", @translation.id], :order => '`translations`.id')
      if request.xhr?
        links << link_to_remote(image_tag('std/go_left.png', :title => _("Previous")), :update => 'translations_element', :url => {:action => :show, :id => prev.id}) if prev
        links << link_to_remote(image_tag('std/go_right.png', :title => _("Next")), :update => 'translations_element', :url => {:action => :show, :id => nex.id}) if nex
      else
        if prev
          links << nil
        end
        if nex
          links << nil
        end
      end
    end
    return content_tag(:span, links.compact.join(' | ').html_safe, :class => 'std_links')
  end


  # Author:: Sylvain Abélard
  # Version:: 17
  # Last Update:: 2013-03-19 15:06:52 UTC
  # Status:: <%= _(%q{Validation Pending}) %>


  def bottom_links_for_edit(opts={})

    links = []
    if request.xhr?
      links << link_to_remote(image_tag('std/show.png', :title => _('Show')), :update => 'translations_element', :url => {:action => :show, :id => @translation, :version => params[:version]})
    else
      links << nil
    end
    links << if @pres_mode == :list_zoom
      %Q{<a href="#" data-confirm="#{ _('Do you really want to delete %{record}?') % {:record => @translation.disp_name} }" data-method="post" onclick="new Ajax.Updater('translations_element', '#{ "/#{params[:lang]}" if params[:lang] }/translations/destroy/#{ @translation.id }', {asynchronous:true, evalScripts:true});location.href='#translations_element'; return false;"><img src="/images/default/s.gif" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" width="16" /> #{ _(%q{Destroy}) }</a>}
    else
      %Q{<a data-confirm="#{ _('Do you really want to delete %{record}?') % {:record => @translation.disp_name} }" data-method="post" href="#{ "/#{params[:lang]}" if params[:lang] }/translations/destroy/#{ @translation.id }"><img src="/images/default/s.gif" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" width="16" /> #{ _(%q{Destroy}) }</a>}
    end
    links << if @pres_mode == :list_zoom
      %Q{<a href="#" onclick="new Ajax.Updater('translations_element', '#{ "/#{params[:lang]}" if params[:lang] }/translations/index', {asynchronous:true, evalScripts:true});location.href='#translations_element'; return false;"><img src="/images/page_icons/anchor.png" alt="#{ _(%q{Translations}) }" title="#{ _(%q{Translations}) }"/> #{ _(%q{Translations}) }</a>}
    else
      %Q{<a href="#{ "/#{params[:lang]}" if params[:lang] }/translations/index"><img src="/images/page_icons/anchor.png" alt="#{ _(%q{Translations}) }" title="#{ _(%q{Translations}) }"/> #{ _(%q{Translations}) }</a>}
    end
    prev = Translation.first(:select => '`translations`.id', :conditions => ["`translations`.id < ?", @translation.id], :order => '`translations`.id DESC')
    nex = Translation.first(:select => '`translations`.id', :conditions => ["`translations`.id > ?", @translation.id], :order => '`translations`.id')
    if request.xhr?
      links << link_to_remote(image_tag('std/go_left.png', :title => _('Previous')), :update => 'translations_element', :url => {:action => :edit, :id => prev.id}) if prev
      links << link_to_remote(image_tag('std/go_right.png', :title => _('Next')), :update => 'translations_element', :url => {:action => :edit, :id => nex.id}) if nex
    else
      if prev
        links << nil
      end
      if nex
        links << nil
      end
    end
    return content_tag(:span, links.compact.join(' | ').html_safe, :class => 'std_links')
  end

end
