# encoding: utf-8
################################################
## This file and all its content belong to Faveod S.A.S unless a commercial
## contract signed by a representant of Faveod S.A.S states otherwise.
##########
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################
## This has been generated by Faveod Generator on Thu Oct 31 16:41:16 +0100 2013
## It should be placed at 'app/helpers/users_helper.rb'
## All manual modifications will be destroyed on next generation
################################################


module UsersHelper


  # Generally used for list actions.
  #
  # Author:: Yann Azoury
  # Version:: 12
  # Last Update:: 2013-01-29 23:35:49 UTC
  # Status:: Validation Pending


  def links_for_list_element(row, opts={})
    return "" if @no_row_links
    html = []
    if @pres_mode == :list_zoom
      html << link_to_remote(image_tag('std/show.png', :title => _('Show')),
      :url => {:controller => :users, :action => :show, :id => row.id},
      :update => "users_element")
      html << link_to_remote(image_tag('std/edit.png', :title => _('Edit')),
      :url => {:controller => :users, :action => :edit, :id => row.id},
      :update => "users_element")
    else
      html << if @pres_mode == :list_zoom
        %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('users_element', '#{ "/#{params[:lang]}" if params[:lang] }/users/show/#{ row.id }', {asynchronous:true, evalScripts:true});location.href='#users_element'; return false;" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/show.png" alt="#{ _(%q{Show}) }" title="#{ _(%q{Show}) }" /></a>}
      else
        %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/users/show/#{ row.id }" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/show.png" alt="#{ _(%q{Show}) }" title="#{ _(%q{Show}) }" /></a>}
      end
      html << if @pres_mode == :list_zoom
        %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('users_element', '#{ "/#{params[:lang]}" if params[:lang] }/users/edit/#{ row.id }', {asynchronous:true, evalScripts:true});location.href='#users_element'; return false;" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/page_icons/page_white_paintbrush.png" alt="#{ _(%q{Edit}) }" title="#{ _(%q{Edit}) }" /></a>}
      else
        %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/users/edit/#{ row.id }" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/page_icons/page_white_paintbrush.png" alt="#{ _(%q{Edit}) }" title="#{ _(%q{Edit}) }" /></a>}
      end
      html << nil
    end
    html << if @pres_mode == :list_zoom
      %Q{<a href="#" data-confirm="#{ _('Do you really want to delete %{record}?') %
      {:record => @user.disp_name} }" data-method="post" onclick="new Ajax.Updater('users_element', '#{ "/#{params[:lang]}" if params[:lang] }/users/destroy/#{ @user.id }', {asynchronous:true, evalScripts:true});location.href='#users_element'; return false;" title="#{ _(%q{Deletes an object or list of objects from the database.}) }"><img src="/images/page_icons/cancel.png" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" /></a>}
    else
      %Q{<a data-confirm="#{ _('Do you really want to delete %{record}?') %
      {:record => @user.disp_name} }" data-method="post" href="#{ "/#{params[:lang]}" if params[:lang] }/users/destroy/#{ @user.id }" title="#{ _(%q{Deletes an object or list of objects from the database.}) }"><img src="/images/page_icons/cancel.png" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" /></a>}
    end
    return html.compact.join(' | ').html_safe
  end


  # Author:: Sylvain Abélard
  # Version:: 17
  # Last Update:: 2013-03-19 15:06:38 UTC
  # Status:: Validation Pending


  def bottom_links_for_show(opts={})

    links = []
    if request.xhr?
      links << link_to_remote(image_tag('std/edit.png', :title => _("Edit")), :update => 'users_element', :url => {:action => :edit, :id => @user, :version => params[:version]})
    else
      links << if @pres_mode == :list_zoom
        %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('users_element', '#{ "/#{params[:lang]}" if params[:lang] }/users/edit/#{ @user.id }', {asynchronous:true, evalScripts:true});location.href='#users_element'; return false;" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/page_icons/page_white_paintbrush.png" alt="#{ _(%q{Edit}) }" title="#{ _(%q{Edit}) }" /> #{ _(%q{Edit}) }</a>}
      else
        %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/users/edit/#{ @user.id }" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/page_icons/page_white_paintbrush.png" alt="#{ _(%q{Edit}) }" title="#{ _(%q{Edit}) }" /> #{ _(%q{Edit}) }</a>}
      end
    end
    links << if @pres_mode == :list_zoom
      %Q{<a href="#" data-confirm="#{ _('Do you really want to delete %{record}?') % {:record => @user.disp_name} }" data-method="post" onclick="new Ajax.Updater('users_element', '#{ "/#{params[:lang]}" if params[:lang] }/users/destroy/#{ @user.id }', {asynchronous:true, evalScripts:true});location.href='#users_element'; return false;" title="#{ _(%q{Deletes an object or list of objects from the database.}) }"><img src="/images/page_icons/cancel.png" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" /> #{ _(%q{Destroy}) }</a>}
    else
      %Q{<a data-confirm="#{ _('Do you really want to delete %{record}?') % {:record => @user.disp_name} }" data-method="post" href="#{ "/#{params[:lang]}" if params[:lang] }/users/destroy/#{ @user.id }" title="#{ _(%q{Deletes an object or list of objects from the database.}) }"><img src="/images/page_icons/cancel.png" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" /> #{ _(%q{Destroy}) }</a>}
    end
    links << if @pres_mode == :list_zoom
      %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('users_element', '#{ "/#{params[:lang]}" if params[:lang] }/users/index', {asynchronous:true, evalScripts:true});location.href='#users_element'; return false;" rel="nofollow" title="#{ _(%q{Index of all users.}) }"><img src="/images/page_icons/user.png" alt="#{ _(%q{Users}) }" title="#{ _(%q{Users}) }"/> #{ _(%q{Users}) }</a>}
    else
      %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/users/index" rel="nofollow" title="#{ _(%q{Index of all users.}) }"><img src="/images/page_icons/user.png" alt="#{ _(%q{Users}) }" title="#{ _(%q{Users}) }"/> #{ _(%q{Users}) }</a>}
    end
    unless opts[:no_sibling]
      prev = User.first(:select => '`users`.id', :conditions => ["`users`.id < ?", @user.id], :order => '`users`.id DESC')
      nex = User.first(:select => '`users`.id', :conditions => ["`users`.id > ?", @user.id], :order => '`users`.id')
      if request.xhr?
        links << link_to_remote(image_tag('std/go_left.png', :title => _("Previous")), :update => 'users_element', :url => {:action => :show, :id => prev.id}) if prev
        links << link_to_remote(image_tag('std/go_right.png', :title => _("Next")), :update => 'users_element', :url => {:action => :show, :id => nex.id}) if nex
      else
        if prev
          links << if @pres_mode == :list_zoom
            %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('users_element', '#{ "/#{params[:lang]}" if params[:lang] }/users/show/#{ prev.id }', {asynchronous:true, evalScripts:true});location.href='#users_element'; return false;" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/go_left.png" alt="#{ _(%q{Previous}) }" title="#{ _(%q{Previous}) }"/></a>}
          else
            %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/users/show/#{ prev.id }" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/go_left.png" alt="#{ _(%q{Previous}) }" title="#{ _(%q{Previous}) }"/></a>}
          end
        end
        if nex
          links << if @pres_mode == :list_zoom
            %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('users_element', '#{ "/#{params[:lang]}" if params[:lang] }/users/show/#{ nex.id }', {asynchronous:true, evalScripts:true});location.href='#users_element'; return false;" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/go_right.png" alt="#{ _(%q{Next}) }" title="#{ _(%q{Next}) }"/></a>}
          else
            %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/users/show/#{ nex.id }" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/go_right.png" alt="#{ _(%q{Next}) }" title="#{ _(%q{Next}) }"/></a>}
          end
        end
      end
    end
    return content_tag(:span, links.compact.join(' | ').html_safe, :class => 'std_links')
  end


  # Author:: Sylvain Abélard
  # Version:: 17
  # Last Update:: 2013-03-19 15:06:52 UTC
  # Status:: Validation Pending


  def bottom_links_for_edit(opts={})

    links = []
    if request.xhr?
      links << link_to_remote(image_tag('std/show.png', :title => _('Show')), :update => 'users_element', :url => {:action => :show, :id => @user, :version => params[:version]})
    else
      links << if @pres_mode == :list_zoom
        %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('users_element', '#{ "/#{params[:lang]}" if params[:lang] }/users/show/#{ @user.id }', {asynchronous:true, evalScripts:true});location.href='#users_element'; return false;" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/show.png" alt="#{ _(%q{Show}) }" title="#{ _(%q{Show}) }" /> #{ _(%q{Show}) }</a>}
      else
        %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/users/show/#{ @user.id }" rel="nofollow" title="#{ _(%q{Display the record.}) }"><img src="/images/std/show.png" alt="#{ _(%q{Show}) }" title="#{ _(%q{Show}) }" /> #{ _(%q{Show}) }</a>}
      end
    end
    links << if @pres_mode == :list_zoom
      %Q{<a href="#" data-confirm="#{ _('Do you really want to delete %{record}?') % {:record => @user.disp_name} }" data-method="post" onclick="new Ajax.Updater('users_element', '#{ "/#{params[:lang]}" if params[:lang] }/users/destroy/#{ @user.id }', {asynchronous:true, evalScripts:true});location.href='#users_element'; return false;" title="#{ _(%q{Deletes an object or list of objects from the database.}) }"><img src="/images/page_icons/cancel.png" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" /> #{ _(%q{Destroy}) }</a>}
    else
      %Q{<a data-confirm="#{ _('Do you really want to delete %{record}?') % {:record => @user.disp_name} }" data-method="post" href="#{ "/#{params[:lang]}" if params[:lang] }/users/destroy/#{ @user.id }" title="#{ _(%q{Deletes an object or list of objects from the database.}) }"><img src="/images/page_icons/cancel.png" alt="#{ _(%q{Destroy}) }" title="#{ _(%q{Destroy}) }" /> #{ _(%q{Destroy}) }</a>}
    end
    links << if @pres_mode == :list_zoom
      %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('users_element', '#{ "/#{params[:lang]}" if params[:lang] }/users/index', {asynchronous:true, evalScripts:true});location.href='#users_element'; return false;" rel="nofollow" title="#{ _(%q{Index of all users.}) }"><img src="/images/page_icons/user.png" alt="#{ _(%q{Users}) }" title="#{ _(%q{Users}) }"/> #{ _(%q{Users}) }</a>}
    else
      %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/users/index" rel="nofollow" title="#{ _(%q{Index of all users.}) }"><img src="/images/page_icons/user.png" alt="#{ _(%q{Users}) }" title="#{ _(%q{Users}) }"/> #{ _(%q{Users}) }</a>}
    end
    prev = User.first(:select => '`users`.id', :conditions => ["`users`.id < ?", @user.id], :order => '`users`.id DESC')
    nex = User.first(:select => '`users`.id', :conditions => ["`users`.id > ?", @user.id], :order => '`users`.id')
    if request.xhr?
      links << link_to_remote(image_tag('std/go_left.png', :title => _('Previous')), :update => 'users_element', :url => {:action => :edit, :id => prev.id}) if prev
      links << link_to_remote(image_tag('std/go_right.png', :title => _('Next')), :update => 'users_element', :url => {:action => :edit, :id => nex.id}) if nex
    else
      if prev
        links << if @pres_mode == :list_zoom
          %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('users_element', '#{ "/#{params[:lang]}" if params[:lang] }/users/edit/#{ prev.id }', {asynchronous:true, evalScripts:true});location.href='#users_element'; return false;" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/std/go_left.png" alt="#{ _(%q{Previous}) }" title="#{ _(%q{Previous}) }"/></a>}
        else
          %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/users/edit/#{ prev.id }" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/std/go_left.png" alt="#{ _(%q{Previous}) }" title="#{ _(%q{Previous}) }"/></a>}
        end
      end
      if nex
        links << if @pres_mode == :list_zoom
          %Q{<a href="#" data-method="get" onclick="new Ajax.Updater('users_element', '#{ "/#{params[:lang]}" if params[:lang] }/users/edit/#{ nex.id }', {asynchronous:true, evalScripts:true});location.href='#users_element'; return false;" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/std/go_right.png" alt="#{ _(%q{Next}) }" title="#{ _(%q{Next}) }"/></a>}
        else
          %Q{<a data-method="get" href="#{ "/#{params[:lang]}" if params[:lang] }/users/edit/#{ nex.id }" rel="nofollow" title="#{ _(%q{Load the data to fill the edit form.}) }"><img src="/images/std/go_right.png" alt="#{ _(%q{Next}) }" title="#{ _(%q{Next}) }"/></a>}
        end
      end
    end
    return content_tag(:span, links.compact.join(' | ').html_safe, :class => 'std_links')
  end


  # Displays details about series
  #
  # Author:: Sylvain Abélard
  # Version:: 1
  # Last Update:: 2009-10-05 13:31:56 UTC
  # Status:: In Progress


  def series_details(s, txt=nil)
    return 'empty' if s.blank?
    info = "#{s.calculation}"
    info << " of #{s.field.name}" if s.field
      info << " by #{s.key_field.name}" if s.key_field
        details = txt || info
        content_tag(:span,
        content_tag(:span, '&nbsp;&nbsp;&nbsp;', :style => "background-color: #{s.html_color}; border: 1px inset gray;") +
        " #{s.disp_name} [#{details}]",
        :title => info,
        :class => "report_#{s.serie_type.downcase}")
      end

    end
