# encoding: utf-8
################################################
## This file and all its content belong to Faveod S.A.S unless a commercial
## contract signed by a representant of Faveod S.A.S states otherwise.
##########
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################
## This has been generated by Faveod Generator on Thu Oct 31 16:41:16 +0100 2013
## It should be placed at 'test/unit/system_setting_test.rb'
## All manual modifications will be destroyed on next generation
################################################


require 'test_helper'

class SystemSettingTest < ActiveSupport::TestCase

  test "Data still valid" do
    SystemSetting.all.each do |system_setting|
      assert(system_setting.valid?)
    end
  end

  test "SystemSetting[:name] shortcut works" do
    SystemSetting.create({:name => 'test-name', :value => 'test-content'})
    assert(SystemSetting[:"test-name"] == 'test-content')
  end

end
